name: Helm Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1
      
      - name: Add Timescale Chart Repo
        run: helm repo add timescale https://charts.timescale.com/

      - name: Update Chart Dependencies
        run: helm repo update

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
      #     if [[ -n "$changed" ]]; then
      #       echo "changed=true" >> "$GITHUB_OUTPUT"
      #     fi

      - name: Run chart-testing (lint)
        # if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        # if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.8.0

      - name: Install Helm Chart
        # if: steps.list-changed.outputs.changed == 'true'
        run: helm install doku ./charts/doku --namespace doku --create-namespace

      - name: wait
        run: sleep 120
      
      - name: Print pod status
        run: |
          kubectl get pods -n doku

      - name: Print logs for a pod with label
        run: |
          kubectl logs -n doku -l app=doku
      
      - name: Check if pods are running
        run: |
          PODS_STATUS=$(kubectl get pods -l app=doku -n doku -o jsonpath="{.items[*].status.phase}")
          if [ "$STATUS" != "Running" ]; then
            echo "Pod is not in Running state: $STATUS"
            exit 1
          fi
          echo "All pods are in the Running state."